name: sample get user info
on:
  workflow_dispatch: {}

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: call curl
        run: |
          curl https://api.github.com/users/takafumi-ko